Feat/Login state caching
SwEnt-Group8/Street-work-app pull request #193
Opened 2024-12-05 10:19 UTC by SaturneV

### Summary

This Pull Request implements login caching, meaning that once the user is logged in with his google account, the application starts directly on the Map. This feature also implements the ability to see the user score and username on the application even when not connected to the Internet.

Implementing this function required firstly implementing a function that checks the application's connectivity to decide whether or not to load the user from the database or cache. It was also necessary to implement a simple Splash Screen to wait for the user to load before displaying the application.

This PR cherry picks commits from the soon to be closed PR https://github.com/SwEnt-Group8/Street-work-app/pull/166 due to features separation.

### Changes

- Add `NewtorkUtils.kt` file.
- Implement `isInternetAvailable` function in `NewtorkUtils.kt` file.
- Add a `SplashScreen.kt` file with a `SplashScreen` composable.
- Implement the login caching logic in `MainActivity.kt`.
- Implement the login caching logic in `SignIn.kt`.

### Tests

- Modify tests to implement the new feature signature and parameters.
- Add an UI test to test the `SplashScreen` composable.
- **TBD**

2024-12-05 21:19 UTC, tercierp commented
After some tests there is a problem with the markers when you get connected for the second time.
It's as if calling up the map doesn't call up the markers, but I'm connected and if I change screen and come back to the map the markers appear.
<p align="center">
  <img src="https://github.com/user-attachments/assets/858948ff-0674-4b93-8ea4-6659610dd1fa" alt="image" width="346">
</p>

2024-12-05 22:06 UTC, tercierp requested changes
I'll let you respond to my comments, especially the one about markers disappearing after a user cache in. Thanks for your contribution!

2024-12-06 09:31 UTC, SaturneV commented on app/src/main/java/com/android/streetworkapp/MainActivity.kt
> +        userViewModel.getUserByUidAndSetAsCurrentUser(uid!!)
I agree with you, I added a check.

2024-12-06 09:39 UTC, SaturneV commented
I fixed the map that wasn't displaying the markers by forcing the map to load the parks when starting the composable. I'll let you check if it works on your side. Good catch!

2024-12-06 17:39 UTC, tercierp approved these changes

2024-12-06 17:39 UTC, tercierp commented
Good patch this time I can't break the markers on the map, merged !

2024-12-06 17:39 UTC, merged